# Generated by Django 4.2.30 on 2026-04-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_mashina"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mashina",
            options={"verbose_name": "mashina", "verbose_name_plural": "mashinalar"},
        ),
    ]
